export type GenericStatus = "active" | "inactive" | "archived" | "connected" | "disconnected" | "pending" | string;

const STATUS_LABEL: Record<string, string> = {
  active: "Ativo",
  inactive: "Inativo",
  archived: "Arquivado",
  connected: "Conectado",
  disconnected: "Desconectado",
  connecting: "Conectando",
  reconnecting: "Reconectando",
  logged_out: "Desconectado (logout)",
  requires_repair: "Precisa reconectar",
  needs_attention: "Precisa de atenção",
  syncing: "Sincronizando",
  pending: "Pendente",
  draft: "Rascunho",
  scheduled: "Agendado",
  publishing: "Publicando",
  in_progress: "Em andamento",
  completed: "Concluído",
  cancelled: "Cancelado",
  running: "Rodando",
  blocked: "Bloqueado",
  skipped: "Ignorado",
  waiting_for_approval: "Aguardando aprovação",
  ready: "Pronto",
  failed: "Falhou",
  published: "Publicado",
  dispatched: "Despachado",
  claimed: "Reivindicado",
  dead_lettered: "Não entregue",
  unknown_outcome: "Resultado desconhecido",
  confirmed_published: "Publicado confirmado",
  confirmed_not_published: "Não publicado confirmado",
  inconclusive: "Inconclusivo",
  unverified: "Não verificado",
  verified: "Verificado",
  mismatch: "Divergência",
  not_supported: "Não suportado",
  reprocessed: "Reprocessado",
  superseded: "Substituído",
  validating: "Validando",
  validated: "Validado",
  validation_failed: "Validação falhou",
  info: "Informativo",
  warning: "Atenção",
  critical: "Crítico",
  healthy: "Saudável",
  degraded: "Atenção",
  unhealthy: "Crítico",
  pass: "OK",
  warn: "Atenção",
  fail: "Falhou",
  acknowledged: "Reconhecido",
  resolved: "Resolvido",
  dismissed: "Dispensado",
};

const STATUS_CLASSES: Record<string, string> = {
  active: "text-status-active bg-status-active-bg",
  connected: "text-status-active bg-status-active-bg",
  completed: "text-status-active bg-status-active-bg",
  syncing: "text-primary bg-accent-soft",
  running: "text-primary bg-accent-soft",
  waiting_for_approval: "text-primary bg-accent-soft",
  blocked: "text-status-archived bg-status-archived-bg",
  skipped: "text-status-archived bg-status-archived-bg",
  inactive: "text-status-inactive bg-status-inactive-bg",
  pending: "text-status-inactive bg-status-inactive-bg",
  scheduled: "text-status-inactive bg-status-inactive-bg",
  publishing: "text-primary bg-accent-soft",
  archived: "text-status-archived bg-status-archived-bg",
  disconnected: "text-status-archived bg-status-archived-bg",
  connecting: "text-primary bg-accent-soft",
  reconnecting: "text-amber-700 bg-amber-50",
  logged_out: "text-status-archived bg-status-archived-bg",
  requires_repair: "text-red-600 bg-red-50",
  needs_attention: "text-amber-700 bg-amber-50",
  cancelled: "text-status-archived bg-status-archived-bg",
  draft: "text-status-archived bg-status-archived-bg",
  in_progress: "text-primary bg-accent-soft",
  ready: "text-status-active bg-status-active-bg",
  failed: "text-red-600 bg-red-50",
  published: "text-status-active bg-status-active-bg",
  dispatched: "text-status-active bg-status-active-bg",
  claimed: "text-primary bg-accent-soft",
  dead_lettered: "text-red-600 bg-red-50",
  unknown_outcome: "text-amber-700 bg-amber-50",
  confirmed_published: "text-status-active bg-status-active-bg",
  confirmed_not_published: "text-red-600 bg-red-50",
  inconclusive: "text-amber-700 bg-amber-50",
  unverified: "text-status-inactive bg-status-inactive-bg",
  verified: "text-status-active bg-status-active-bg",
  mismatch: "text-red-600 bg-red-50",
  not_supported: "text-status-archived bg-status-archived-bg",
  reprocessed: "text-primary bg-accent-soft",
  superseded: "text-status-archived bg-status-archived-bg",
  validating: "text-primary bg-accent-soft",
  validated: "text-status-active bg-status-active-bg",
  validation_failed: "text-red-600 bg-red-50",
  info: "text-primary bg-accent-soft",
  warning: "text-amber-700 bg-amber-50",
  critical: "text-red-600 bg-red-50",
  healthy: "text-status-active bg-status-active-bg",
  degraded: "text-amber-700 bg-amber-50",
  unhealthy: "text-red-600 bg-red-50",
  pass: "text-status-active bg-status-active-bg",
  warn: "text-amber-700 bg-amber-50",
  fail: "text-red-600 bg-red-50",
  acknowledged: "text-status-inactive bg-status-inactive-bg",
  resolved: "text-status-active bg-status-active-bg",
  dismissed: "text-status-archived bg-status-archived-bg",
};

export function StatusBadge({ status }: { status: GenericStatus }) {
  const classes = STATUS_CLASSES[status] ?? "text-ink-muted bg-surface-sunken";
  const label = STATUS_LABEL[status] ?? status;
  return <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${classes}`}>{label}</span>;
}
