export type GenericStatus = "active" | "inactive" | "archived" | "connected" | "disconnected" | "pending" | string;

const STATUS_LABEL: Record<string, string> = {
  active: "Ativo",
  inactive: "Inativo",
  archived: "Arquivado",
  connected: "Conectado",
  disconnected: "Desconectado",
  connecting: "Conectando",
  reconnecting: "Reconectando",
  logged_out: "Desconectado (logout)",
  requires_repair: "Precisa reconectar",
  needs_attention: "Precisa de atenção",
  syncing: "Sincronizando",
  pending: "Pendente",
  draft: "Rascunho",
  scheduled: "Agendado",
  publishing: "Publicando",
  in_progress: "Em andamento",
  completed: "Concluído",
  cancelled: "Cancelado",
  canceled: "Cancelado",
  trial: "Período de teste",
  trial_expired: "Teste expirado",
  past_due: "Pagamento pendente",
  suspended: "Suspenso",
  void: "Anulada",
  uncollectible: "Incobrável",
  paid: "Paga",
  running: "Rodando",
  blocked: "Bloqueado",
  skipped: "Ignorado",
  waiting_for_approval: "Aguardando aprovação",
  ready: "Pronto",
  failed: "Falhou",
  published: "Publicado",
  dispatched: "Despachado",
  claimed: "Reivindicado",
  dead_lettered: "Não entregue",
  unknown_outcome: "Resultado desconhecido",
  confirmed_published: "Publicado confirmado",
  confirmed_not_published: "Não publicado confirmado",
  inconclusive: "Inconclusivo",
  unverified: "Não verificado",
  verified: "Verificado",
  mismatch: "Divergência",
  not_supported: "Não suportado",
  reprocessed: "Reprocessado",
  superseded: "Substituído",
  validating: "Validando",
  validated: "Validado",
  validation_failed: "Validação falhou",
  info: "Informativo",
  warning: "Atenção",
  critical: "Crítico",
  healthy: "Saudável",
  degraded: "Atenção",
  unhealthy: "Crítico",
  pass: "OK",
  warn: "Atenção",
  fail: "Falhou",
  acknowledged: "Reconhecido",
  resolved: "Resolvido",
  dismissed: "Dispensado",
  sent: "Enviada",
  viewed: "Visualizada",
  accepted: "Aceita",
  rejected: "Recusada",
  expired: "Expirada",
  done: "Concluída",
  open: "Aberta",
  won: "Ganho",
  lost: "Perdido",
};

const STATUS_CLASSES: Record<string, string> = {
  active: "text-status-active bg-status-active-bg",
  connected: "text-status-active bg-status-active-bg",
  completed: "text-status-active bg-status-active-bg",
  syncing: "text-primary bg-accent-soft",
  running: "text-primary bg-accent-soft",
  waiting_for_approval: "text-primary bg-accent-soft",
  blocked: "text-status-archived bg-status-archived-bg",
  skipped: "text-status-archived bg-status-archived-bg",
  inactive: "text-status-inactive bg-status-inactive-bg",
  pending: "text-status-inactive bg-status-inactive-bg",
  scheduled: "text-status-inactive bg-status-inactive-bg",
  publishing: "text-primary bg-accent-soft",
  archived: "text-status-archived bg-status-archived-bg",
  disconnected: "text-status-archived bg-status-archived-bg",
  connecting: "text-primary bg-accent-soft",
  reconnecting: "text-warning bg-warning-bg",
  logged_out: "text-status-archived bg-status-archived-bg",
  requires_repair: "text-danger bg-danger-bg",
  needs_attention: "text-warning bg-warning-bg",
  cancelled: "text-status-archived bg-status-archived-bg",
  canceled: "text-status-archived bg-status-archived-bg",
  draft: "text-status-archived bg-status-archived-bg",
  in_progress: "text-primary bg-accent-soft",
  ready: "text-status-active bg-status-active-bg",
  failed: "text-danger bg-danger-bg",
  published: "text-status-active bg-status-active-bg",
  dispatched: "text-status-active bg-status-active-bg",
  claimed: "text-primary bg-accent-soft",
  dead_lettered: "text-danger bg-danger-bg",
  unknown_outcome: "text-warning bg-warning-bg",
  confirmed_published: "text-status-active bg-status-active-bg",
  confirmed_not_published: "text-danger bg-danger-bg",
  inconclusive: "text-warning bg-warning-bg",
  unverified: "text-status-inactive bg-status-inactive-bg",
  verified: "text-status-active bg-status-active-bg",
  mismatch: "text-danger bg-danger-bg",
  not_supported: "text-status-archived bg-status-archived-bg",
  reprocessed: "text-primary bg-accent-soft",
  superseded: "text-status-archived bg-status-archived-bg",
  validating: "text-primary bg-accent-soft",
  validated: "text-status-active bg-status-active-bg",
  trial: "text-primary bg-accent-soft",
  trial_expired: "text-danger bg-danger-bg",
  past_due: "text-warning bg-warning-bg",
  suspended: "text-danger bg-danger-bg",
  void: "text-status-archived bg-status-archived-bg",
  uncollectible: "text-danger bg-danger-bg",
  paid: "text-status-active bg-status-active-bg",
  validation_failed: "text-danger bg-danger-bg",
  info: "text-primary bg-accent-soft",
  warning: "text-warning bg-warning-bg",
  critical: "text-danger bg-danger-bg",
  healthy: "text-status-active bg-status-active-bg",
  degraded: "text-warning bg-warning-bg",
  unhealthy: "text-danger bg-danger-bg",
  pass: "text-status-active bg-status-active-bg",
  warn: "text-warning bg-warning-bg",
  fail: "text-danger bg-danger-bg",
  acknowledged: "text-status-inactive bg-status-inactive-bg",
  resolved: "text-status-active bg-status-active-bg",
  dismissed: "text-status-archived bg-status-archived-bg",
  sent: "text-primary bg-accent-soft",
  viewed: "text-primary bg-accent-soft",
  accepted: "text-status-active bg-status-active-bg",
  rejected: "text-danger bg-danger-bg",
  expired: "text-status-archived bg-status-archived-bg",
  done: "text-status-active bg-status-active-bg",
  open: "text-primary bg-accent-soft",
  won: "text-status-active bg-status-active-bg",
  lost: "text-danger bg-danger-bg",
};

export function StatusBadge({ status }: { status: GenericStatus }) {
  const classes = STATUS_CLASSES[status] ?? "text-ink-muted bg-surface-sunken";
  const label = STATUS_LABEL[status] ?? status;
  return <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${classes}`}>{label}</span>;
}
